// <auto-generated />
namespace FindInCn.Shared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fk_user_favorites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_user_favorites));
        
        string IMigrationMetadata.Id
        {
            get { return "201605311351487_fk_user_favorites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
