// <auto-generated />
namespace FindInCn.Shared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201605201243051_idproperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
